import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from "next/image";
import { useState } from "react";
import transistor from "../public/transistor.jpg";
import LED from "../public/LED.gif";
import signal1 from "../public/signal1.png";
import zener1 from "../public/zener1.png";
import power1 from "../public/power1.jpg";
import solar1 from "../public/solar1.jpg";
import solar2 from "../public/solar2.png";
import mosfet1 from "../public/mosfet.jpg";



export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>EE3080</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
      <nav className="pt-10 mb-12 flex justify-between dark:text-white sticky top-0 z-10 m-0 md:bg-white dark:bg-gray-900">
            <h1 className="font-burtons text-xl">EE3080 Introduction to Transistors</h1>
            <ul class="flex flex-col bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-16 md:mt-0 m md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
              <li>
                <a href="#Intro" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Introduction</a>
              </li>
              <li>
                <a href="#LED" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">LED</a>
              </li>
              <li>
                <a href="#Diode" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Diode</a>
              </li>
              <li>
                <a href="#Solar Cell" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Solar Cell</a>
              </li>
              <li>
                <a href="#MOSFET" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">MOSFET</a>
              </li>
              <li>
                <a href="#BJT" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">BJT</a>
              </li>
              <li>
                <a href="#About Us" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About Us</a>
              </li>
            </ul>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>

            </ul>
          </nav>
        <section className="min-h-screen" id="Intro">
          <div className="h-20"></div>
          <div className="text-center p-10 py-10" >
            <h2 className="text-5xl py-2 font-medium text-teal-600 dark:text-teal-400 md:text-6xl">
              Introduction to transistors
            </h2>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              A transistor is a miniature electronic component that can work as either as a switch or as an amplifier. It is made from semiconductors, which can behave either a conductor or a insulator when treated with impurities known as doping.
            </p>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={transistor} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section className="min-h-screen" id="LED">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">LED</h3>
            

            <h5 className="py-1  text-gray-800 dark:text-gray-300 font-bold">Background</h5>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              - LED is a specialised form of PN junction that emits light when current flows through it. <br/>
              - LED is made from compound such as Gallium Arsenide as material such as silicon and germanium do not emit light <br/>
              - Under forward bias, Holes from p-type region and electrons from n-type region enter junction and recombine. <br/>
              - When this occurs energy is released, some of which is in the form of light photons.
            </p>
            <Image src={LED} class="rounded-xl"/>
            <h5 className="py-1  text-gray-800 dark:text-gray-300 font-bold mt-8">LED types</h5>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              - Surface emitting: emits light perpendicular to the plane of the PN junction. <br/>
              - Edge emitting: emits light in a plane parallel to the junction of the PN junction
            </p>
            <h5 className="py-1  text-gray-800 dark:text-gray-300 font-bold">Differences between LED and photodiode</h5>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              - LED converts Electrical energy to light energy, PD light energy to electrical energy <br/>
              - LED is forward-biased while photodiode is reverse-biased <br/>
              - LED made up of GaAs/GaP/GaAsP compounds, while PD is made up of Ge/Si elements. <br/>
            </p>
          </div>
        </section>
        <section className="min-h-screen" id="Diode">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">Diode</h3>
            <h5 className=" text-gray-800 dark:text-gray-300 font-bold text-2xl py-3">Signal Diode</h5>
            <Image src={signal1} class="rounded-xl"/>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Small-signal diodes are constructed as PN diodes with a tiny junction area.

              A smaller junction area gives the diode a smaller junction capacitance.

              This also reduces the reverse recovery time of the diode to a few nanoseconds or less. Small junction capacitance and fast response make the diode suitable for high-frequency applications. The simplest construction of a signal diode is infusing p-type silicon over n-type silicon.
            </p>
            <h5 className=" text-gray-800 dark:text-gray-300 font-bold text-2xl py-3">Zener Diode</h5>
            <Image src={zener1} class="rounded-xl"/>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              A Zener diode exhibits almost the same properties, except the device is specially designed so as to have a reduced breakdown voltage, the so-called Zener voltage. By contrast with the conventional device, a reverse-biased Zener diode exhibits a controlled breakdown and allows the current to keep the voltage across the Zener diode close to the Zener breakdown voltage. Meaning that the zener diode maintains the same voltage(breakdown voltage) across a wide range of currents when zener voltage is met even though voltage supply might increase.voltage curve very steep in reverse bias breakdown

              Zener breakdown occurs in heavily doped junctions in which the transition from the p side to the n side is very abrupt. Under these conditions, the potential barrier separating carriers on the two sides of the junction is very narrow(results in lower breakdown voltage and highly doped so the space-charge region is narrower), and a quantum-mechanical process called quantum tunnelling can take place. In effect, electrons from the p-side valence band are able to tunnel across the barrier into the empty states in the n-side conduction band when a small reverse bias is applied. The result is a strong current from n to p in the diode, causing zener breakdown.

              For diodes with lighter doping or with a graded junction, the avalanche mechanism is the operative breakdown process. In this effect, the electric field in the transition region becomes strong enough under reverse bias to accelerate carriers to quite high kinetic energy.
            </p>
            <h5 className=" text-gray-800 dark:text-gray-300 font-bold text-2xl py-3">Power Diode</h5>
            <Image src={power1} class="rounded-xl"/>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              A Zener diode exhibits almost the same properties, except the device is specially designed so as to have a reduced breakdown voltage, the so-called Zener voltage. By contrast with the conventional device, a reverse-biased Zener diode exhibits a controlled breakdown and allows the current to keep the voltage across the Zener diode close to the Zener breakdown voltage. Meaning that the zener diode maintains the same voltage(breakdown voltage) across a wide range of currents when zener voltage is met even though voltage supply might increase.voltage curve very steep in reverse bias breakdown

              Zener breakdown occurs in heavily doped junctions in which the transition from the p side to the n side is very abrupt. Under these conditions, the potential barrier separating carriers on the two sides of the junction is very narrow(results in lower breakdown voltage and highly doped so the space-charge region is narrower), and a quantum-mechanical process called quantum tunnelling can take place. In effect, electrons from the p-side valence band are able to tunnel across the barrier into the empty states in the n-side conduction band when a small reverse bias is applied. The result is a strong current from n to p in the diode, causing zener breakdown.

              For diodes with lighter doping or with a graded junction, the avalanche mechanism is the operative breakdown process. In this effect, the electric field in the transition region becomes strong enough under reverse bias to accelerate carriers to quite high kinetic energy.
            </p>
          </div>
        </section>
        <section className="min-h-screen" id="Solar Cell">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">Solar Cell</h3>
            <h5 className="py-3 text-gray-800 dark:text-gray-300 font-bold">How does it work?</h5>
            <Image src={solar1} class="rounded-xl"/>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              1. When sunlight shines on the cell, photons (light particles) bombard the upper surface.<br/>
              2. The photons carry their energy down through the cell.<br/>
              3. The photons give up their energy to electrons in the lower, p-type layer. <br/>
              4. The electrons use this energy to jump across the barrier into the upper, n-type layer and escape out into the circuit.<br/>
              5. Flowing around the circuit, the electrons make the lamp light up.<br/>
            </p>
            <h5 className="py-3 text-gray-800 dark:text-gray-300 font-bold">Solar cell and its components</h5>
            <Image src={solar2} class="rounded-xl"/>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <strong>Glass</strong> : It is the outer most layer on the solar cell and has to be sturdy and shiny for better performance of the panel. The main function of solar glass is to protect the solar cells from harsh weather, dirt and dust. It is recommended to use tempered glass with 3mm - 4mmm thickness. <br/>
              <strong>Backsheet</strong> : the rear-most layer of the panel providing both mechanical protection and electrical insulation. It is essentially a protective layer. <br/>
              <strong>Transparent Adhesive</strong> : holds the glass to the rest of the solar cell. <br/>
              <strong>Anti-reflective Coating</strong> : this substance is designed to prevent the light that strikes the cell from bouncing off so that the maximum energy is absorbed into the cell. <br/>
              <strong>Front Contact</strong> - transmits the electric current.<br/>
              <strong>N-Type Semiconductor Layer</strong> : a thin layer of silicon  which  has  been  mixed  with  phosphorous  to make it a better conductor.<br/>
              <strong>P-Type Semiconductor Layer</strong> : This is a thin layer of silicon which has been mixed or doped with boron to make it a better conductor.<br/>
            </p>
          </div>
        </section>
        <section className="min-h-screen" id="MOSFET">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">MOSFET</h3>
            <Image src={mosfet1} class="rounded-xl"/>
          </div>
        </section>
        <section className="min-h-screen" id="BJT">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">BJT</h3>
          </div>
        </section>
        <section className="min-h-screen" id="About Us">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">About Us</h3>
            
          </div>
        </section>
      </main>
    </div>
  );
}
