import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from "next/image";
import { useState } from "react";
import transistor from "../public/transistor.jpg";
import table1 from "../public/table1.png";
import signal1 from "../public/signal1.png";
import zener1 from "../public/zener1.png";
import power from "../public/power1.jpg";
import solar1 from "../public/solar1.jpg";
import solar2 from "../public/solar2.png";
import mosfet1 from "../public/mosfet.jpg";
import LED2 from "../public/LED2.png";
import ledfab1 from "../public/ledfab1.png";
import ledfab2 from "../public/ledfab2.png";
import fab2 from "../public/fab2.png";
import fab3 from "../public/fab3.png";
import fab4 from "../public/fab4.png";
import fab5 from "../public/fab5.png";
import fab6 from "../public/fab6.png";
import fab7 from "../public/fab7.png";
import fab8 from "../public/fab8.png";
import power1 from "../public/power1.png";
import solarcurve1 from "../public/solarcurve1.png";
import solarcurve2 from "../public/solarcurve2.png";
import fet1 from "../public/fet1.png";
import bjt1 from "../public/bjt1.png";
import bjt2 from "../public/bjt2.png";
import bjt3 from "../public/bjt3.jpeg";
import bjt4 from "../public/bjt4.png";
import bjt5 from "../public/bjt5.png";
import bjt6 from "../public/bjt6.png";
import bjt7 from "../public/bjt7.png";
import bjt8 from "../public/bjt8.png";
import bjt9 from "../public/bjt9.png";
import bjt10 from "../public/bjt10.png";
import sim1 from "../public/sim1.png";
import sim2 from "../public/sim2.png";
import sim3 from "../public/sim3.png";
import sim4 from "../public/sim4.png";
import sim5 from "../public/sim5.png";
import sim6 from "../public/sim6.png";
import sim7 from "../public/sim7.png";
import sim8 from "../public/sim8.png";




export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""} >
      <Head>
        <title>EE3080</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-60">
      <nav className="pt-10 mb-12 flex justify-between dark:text-white sticky top-0 z-10 m-0 md:bg-white dark:bg-gray-900">
            <h1 className="font-burtons text-xl">EE3080 Introduction to Transistors</h1>
            <ul class="flex flex-col bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-16 md:mt-0 m md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
              <li>
                <a href="#Intro" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Introduction</a>
              </li>
              <li>
                <a href="#LED" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">LED</a>
              </li>
              <li>
                <a href="#Diode" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Diode</a>
              </li>
              <li>
                <a href="#Solar Cell" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Solar Cell</a>
              </li>
              <li>
                <a href="#BJT" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">BJT</a>
              </li>
              <li>
                <a href="#MOSFET" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">MOSFET</a>
              </li>
              <li>
                <a href="#Simulation" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Simulation</a>
              </li>
              <li>
                <a href="#About Us" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About Us</a>
              </li>
            </ul>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>

            </ul>
          </nav>
        <section className="min-h-screen" id="Intro">
          <div className="h-20"></div>
          <div className="text-center p-10 py-10" >
            <h2 className="text-5xl py-2 font-medium text-teal-600 dark:text-teal-400 md:text-6xl">
              Introduction to transistors
            </h2>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              A transistor is a miniature electronic component that can work as either as a switch or as an amplifier. It is made from semiconductors, which can behave either a conductor or a insulator when treated with impurities known as doping.
            </p>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={transistor} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section className="min-h-screen" id="LED">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">LED</h3>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Background</h5>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            LED is a specialised form of PN junction that emits light.It is built using compound semiconductors such as gallium arsenide and indium phosphide. Commonly used material such as silicon and germanium do not emit light. The table below shows the different colours produced from the different materials.
            </p>
            <Image src={table1} class="rounded-xl" width={350} height={200}/>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">How does it work?</h5>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200">
            The LED  emits light when it is forward biased. Holes from p-type and electrons from n-type enter junction and recombine. When this occurs, energy is released in the form of photons. Below is the LED IV-curve.
            </p>
            <Image src={LED2} class="rounded-xl" width={200} height={200}/>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Fabrication Process</h5>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200">
            Fabrication of LED is similar to diode with additional differences listed below <br/>
            Liquid Phase Epitaxy (LPE) <br/>
            The epitaxy adds impurity to semiconductor crystals which creates a uniform layer of material that has varying electronic densities.
            </p>
            <Image src={ledfab1} class="rounded-xl" width={350} height={200}/>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200">
            Mounting and packaging <br/>
            Typically, wafer’s back is covered with metal which forms an electrical connection with the metal lead of packaging.The other connection is formed by connecting the lead the patterned contacts on the surface of the die by a thin gold wire that is soldered to it.
            </p>
            <Image src={ledfab2} class="rounded-xl" width={350} height={200}/>
          </div>
        </section>
        <section className="min-h-screen" id="Diode">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">Diode</h3>
            <h5 className=" text-gray-800 dark:text-gray-300 font-bold text-2xl py-3">Signal Diode</h5>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            It is a small non-linear semiconductor devices generally used in electronic circuits, where small currents or high frequencies are involved such as in radio, television and digital logic circuits. It has a small junction area which gives the diode a smaller junction capacitance and reduces the reverse recovery time of the diode to a few nanoseconds.. The simplest construction of a signal diode is infusing p-type silicon over n-type silicon.
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Fabrication Process of Signal Diode</h5>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
              Thermal Oxidation
            </p>
            <Image src={fab2} class="rounded-xl" width={150} height={100}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            N-type substrate undergoes wet thermal oxidation to form a layer of Silicon Dioxide (SiO2)
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Photoresist Application
            </p>
            <Image src={fab3} class="rounded-xl" width={150} height={100}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            A layer of positive photoresist is applied onto the surface of the substrate through spin coating, allowing for thickness to be controlled.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Alignment & Exposure
            </p>
            <Image src={fab4} class="rounded-xl" width={150} height={100}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            A mask, containing the intended pattern of the wafer, is placed on top of the photoresist layer. UV Light is shone onto the wafer where only exposed parts of the photoresist will undergo chemical reactions, becoming soluble to the developer.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Development
            </p>
            <Image src={fab5} class="rounded-xl" width={150} height={100}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            The developer is applied to the wafer surface where it will dissolve photoresist exposed to UV. In this case, since positive resist is used, an alkaline developer such as KOH will be utilised.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Etching
            </p>
            <Image src={fab6} class="rounded-xl" width={150} height={100}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            The wafer undergoes Wet Etching where Hydrofluoric Acid (HF) is used to dissolve SiO2. Remaining photoresist layer is removed from the wafer
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Thermal diffusion
            </p>
            <Image src={fab7} class="rounded-xl" width={150} height={100}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            P-type region is formed by exposing the wafer to various Boron sources such Diborane (B2H6) while being heated
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Metalization
            </p>
            <Image src={fab8} class="rounded-xl" width={250} height={150}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            Aluminium contacts are formed on either end of the wafer through Physical Vapour Deposition which involves Argon plasma bombarding a layer of Aluminium. Aluminium atoms that are dislodged travel towards the wafer where it will condense and form a thin layer.
            </p>
            <h5 className=" text-gray-800 dark:text-gray-300 font-bold text-2xl py-3 mt-20">Zener Diode</h5>
            <Image src={zener1} class="rounded-xl" width={200} height={200}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            A Zener diode is designed to have a reduced breakdown voltage, the so-called Zener voltage. It exhibits a controlled breakdown and allows the current to keep the voltage across the Zener diode close to the Zener breakdown voltage.<br/>Zener breakdown occurs in heavily doped junctions in which the transition from the p side to the n side is very abrupt. Under these conditions, the potential barrier separating carriers on the two sides of the junction is very narrow(results in lower breakdown voltage and highly doped so the space-charge region is narrower), and a quantum-mechanical process called quantum tunnelling can take place. In effect, electrons from the p-side valence band are able to tunnel across the barrier into the empty states in the n-side conduction band when a small reverse bias is applied. The result is a strong current from n to p in the diode, causing zener breakdown.<br/>For diodes with lighter doping or with a graded junction, the avalanche mechanism is the operative breakdown process. In this effect, the electric field in the transition region becomes strong enough under reverse bias to accelerate carriers to quite high kinetic energy.
            </p>
            <h5 className=" text-gray-800 dark:text-gray-300 font-bold text-2xl py-3 mt-20">Power Diode</h5>
            <Image src={power} class="rounded-xl" width={200} height={200}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            A power diode has larger junction area from a standard diode to enable a higher current rating.
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">I-V characteristic of power diode</h5>
            <Image src={power1} class="rounded-xl" width={300} height={200}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            The net charge neutrality of the space charge region is still maintained as was the case in the signal diode but the thickness of the space charge region is quite high and deeply penetrated into the N– region.<br/>This is due to its light doping concentration, as we know that the thickness of the space charge region increases with a decrease in doping concentration.<br/>This increased thickness of the depletion region or the space charge region helps the diode to block larger reverse-biased voltage and hence have a greater breakdown voltage.<br/>However, adding this N– layer significantly increases the ohmic resistance of the diode leading to more heat generation during the forwarding conduction state. Hence power diodes come with various mountings for proper heat dissipation.<br/>In signal diodes for forward-biased regions the current increases exponentially however in power diodes, high forward current leads to high ohmic drop which dominates the exponential growth and the curve increases almost linearly.
            </p>
          </div>
        </section>
        <section className="min-h-screen" id="Solar Cell">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">Solar Cell</h3>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200">
            PN Junction Solar cells are semiconductors that convert light to electrical energy. They are also known as PV(Photovoltaic) cells. Individual solar cells are combined to form modules known as solar panels. The solar panels are arranged in parallel and series according to the power requirement.
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">How does it work?</h5>
            <Image src={solar1} class="rounded-xl" width={300} height={200}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
              1. When sunlight shines on the cell, photons (light particles) bombard the upper surface.<br/>
              2. The photons carry their energy down through the cell.<br/>
              3. The photons give up their energy to electrons in the lower, p-type layer. <br/>
              4. The electrons use this energy to jump across the barrier into the upper, n-type layer and escape out into the circuit.<br/>
              5. Flowing around the circuit, the electrons make the lamp light up.<br/>
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Solar cell and its components</h5>
            <Image src={solar2} class="rounded-xl" width={400} height={200}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
              <strong>Glass</strong> : It is the outer most layer on the solar cell and has to be sturdy and shiny for better performance of the panel. The main function of solar glass is to protect the solar cells from harsh weather, dirt and dust. It is recommended to use tempered glass with 3mm - 4mmm thickness. <br/>
              <strong>Backsheet</strong> : the rear-most layer of the panel providing both mechanical protection and electrical insulation. It is essentially a protective layer. <br/>
              <strong>Transparent Adhesive</strong> : holds the glass to the rest of the solar cell. <br/>
              <strong>Anti-reflective Coating</strong> : this substance is designed to prevent the light that strikes the cell from bouncing off so that the maximum energy is absorbed into the cell. <br/>
              <strong>Front Contact</strong> - transmits the electric current.<br/>
              <strong>N-Type Semiconductor Layer</strong> : a thin layer of silicon  which  has  been  mixed  with  phosphorous  to make it a better conductor.<br/>
              <strong>P-Type Semiconductor Layer</strong> : This is a thin layer of silicon which has been mixed or doped with boron to make it a better conductor.<br/>
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Solar Cell I-V characteristic</h5>
            <Image src={solarcurve1} class="rounded-xl" width={400} height={200}/>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200">
            The above graph shows the current-voltage ( I-V ) characteristics of a typical silicon PV cell operating under normal conditions. The power delivered by a single solar cell or panel is the product of its output current and voltage ( I x V ). If the multiplication is done, point for point, for all voltages from short-circuit to open-circuit conditions, the power curve above is obtained for a given radiation level.
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Solar Panel I-V characteristic</h5>
            <Image src={solarcurve2} class="rounded-xl" width={300} height={200}/>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200">
            Photovoltaic panels can be wired or connected together in either series or parallel combinations, or both to increase the voltage or current capacity of the solar array. If the array panels are connected together in a series combination, then the voltage increases and if connected together in parallel then the current increases.<br/>The maximum power point (MPP) of a solar cell is positioned near the bend in the I-V characteristics curve. The corresponding values of Vmp and Imp can be estimated from the open circuit voltage and the short circuit current: Vmp ≅ (0.8–0.90)Voc and Imp ≅ (0.85–0.95)Isc. Since solar cell output voltage and current both depend on temperature, the actual output power will vary with changes in ambient temperature.
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Fabrication Process of Solar Cell</h5>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Step 1: Pre-check and Pretreatment
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            The raw silicon wafer disks first undergo a pre-check during which they are inspected on their geometric shape and thickness conformity and on damages such as cracks, breakages, scratches, or other anomalities.<br/>Following this pre-check, the wafers are split and cleaned with industrial soaps to remove any metal residues, liquids or other production remains from the surface that would otherwise impact the efficiency of that wafer.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Step 2: Texturing
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            For monocrystalline silicon wafers, the most common technique is random pyramid texturing which involves the coverage of the surface with aligned upward-pointing pyramid structures.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Step 3: Acid Cleaning
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
              After texturing, the wafers undergo acidic rinsing (or: acid cleaning). In this step, any post-texturing particle remains are removed from the surface.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Step 4: Diffusion
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            Diffusion is basically the process of adding a dopant to the silicon wafer to make it more electrically conductive. There are basically 2 methods of diffusion: solid-state diffusion and emitter diffusion.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Step 5: Etching & Edge Isolation
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            During diffusion, the n-type phosphorous diffuses not only into the desired wafer surface but also around the edges of the wafer as well as on the backside, creating an electrical path between the front and backside and in this way also preventing electrical isolation between the two sides.<br/>The objective of the etching and edge isolation process is to remove this electrical path around the wafer edge by disk stacking the cells on top of each other and then exposing them to a plasma etching chamber using tetrafluoromethane (CF4) to etch exposed edges.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Step 6: Post-Etching Washing
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            After the etching, particle residues' potential remains on the wafer and the wafer edges. Therefore the wafers need to undergo a second washing to remove the remains of the previous etching process.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Step 7: Anti-Reflective Coating Deposition
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            In addition to surface texturing, AR coating is often applied on the surface to further reduce reflection and increase the amount of light absorbed into the cell.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Step 8: Contact Printing and Drying
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            As the next step, metal inlines are printed on the wafer with the objective to create ohmic contacts. These metal inlines are printed on the rear side of the wafer, which is called backside printing.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Step 9: Testing and Cell Sorting
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            In this final process, the now ready-to-assemble solar cells are tested under simulated sunlight conditions and then classified and sorted according to their efficiencies.
            </p>
          </div>
        </section>
        <section className="min-h-screen" id="BJT">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">BJT</h3>
            <Image src={bjt1} class="rounded-xl" width={400} height={200}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            The Bi-polar Junction Transistors (BJT) are semiconductor devices in which both electrons and holes participate in the conduction process. As compared to the unipolar devices where there is only one type of carrier that take part predominantly in the conduction process. BJT is made up of 2 PN junction that in close contact to interact with each other. And the coupling of 2 p-n junction result in transistor action.<br/>The modern days BJTs are made up of 3 terminals, the base, emitter and collector. The width of the base region is the smallest to allow the carriers injected from emitter to be able to diffuse through the base and reach the base-collector depletion region. While the emitter region has the largest doping concentration where carriers are injected to the base in the active mode. Followed by the collector region which has the smallest doping concentration. <br/>This junctions of the BJT can be biased in different ways. By having a input and output at 2 of the 3 junction respectively, we can have the one without input or output to be the common. Common Base, Common Emitter, Common Collector which also give different IV graphs based on the different biased.
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Common base</h5>
            <Image src={bjt2} class="rounded-xl" width={400} height={200}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            Active region: emitter in reverse and collector in forward <br/>
            Cut-off: both emitter and collector junction in reverse biased <br/>
            Saturation: both emitter-collector junction in forward biased <br/>
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Common emitter</h5>
            <Image src={bjt3} class="rounded-xl" width={400} height={200}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            <strong>Active region</strong>: collector in reverse and emitter in forward<br/><strong>Cut-off</strong>: both emitter and collector junction in reverse biased<br/><strong>Saturation</strong>: both emitter-collector junction in forward biased<br/>In ideal transistors with common-emitter configuration, the Ic for a given Ib should be independent of Vec for Vec &gt 0. This is true if we assume that neutral base width is a constant.<br/>However, the practical BJTs, the width of space charge region extends into the base region varies with the base collector voltage, the neutral base width is hence a function of Vec. the collector current Ic is therefore dependent on Vec.<br/>As the reverse bias to the collector-base junction increases, the neutral base width decreases. The reduce in base width will cause the gradient in minority-carrier concentration to increase. And results in increase in diffusion current  Ic and hence common-emitter gain also increase.
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Common collector</h5>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            The collector terminal will be connected common to the input and the output
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Fabrication of BJT</h5>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Deposition of oxide through CVD
            </p>
            <Image src={bjt4} class="rounded-xl" width={200} height={100}/>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Oxide patterning
            </p>
            <Image src={bjt5} class="rounded-xl" width={300} height={150}/>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Epitaxial deposition
            </p>
            <Image src={bjt6} class="rounded-xl" width={200} height={100}/>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Isolation
            </p>
            <Image src={bjt7} class="rounded-xl" width={150} height={100}/>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Base formation
            </p>
            <Image src={bjt8} class="rounded-xl" width={150} height={100}/>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Emitter and collector isolation
            </p>
            <Image src={bjt9} class="rounded-xl" width={150} height={100}/>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Metal contact formation
            </p>
            <Image src={bjt10} class="rounded-xl" width={150} height={100}/>
            
          </div>
        </section>
        <section className="min-h-screen" id="MOSFET">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">MOSFET</h3>
            <Image src={fet1} class="rounded-xl" width={400} height={200}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            A MOSFET is a four-terminal device having source(S), gate (G), drain (D) and body (B) terminals. In general, The body of the MOSFET is in connection with the source terminal thus forming a three-terminal device such as a field-effect transistor. <br/>
            The semiconductor surface at the below oxide layer which is located between the source and drain terminal can be inverted from p-type to n-type by the application of either a positive or negative gate voltages respectively.  When we apply a repulsive force for the positive gate voltage, then the holes present beneath the oxide layer are pushed downward with the substrate.<br/>
            The depletion region populated by the bound negative charges which are associated with the acceptor atoms. When electrons are reached, a channel is developed. The positive voltage also attracts electrons from the n+ source and drain regions into the channel. Now, if a voltage is applied between the drain and source, the current flows freely between the source and drain and the gate voltage controls the electrons in the channel. Instead of the positive voltage, if we apply a negative voltage, a hole channel will be formed under the oxide layer.
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Fabrication Process</h5>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Oxidation
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            Formation of silicon dioxide layer on the surface of Si wafer<br/>Dry oxidation: lower rate and higher quality<br/>Wet oxidation: higher rate and lower quality
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Deposition
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            Formation a thin film on the surface of Si wafer<br/>Thin film materials: semiconductor, insulator and metal<br/>Typical chemical vapor deposition methods: APCVD, LPCVD and PECVD
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Implantation/diffusion
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            Process steps to specify the doping species and concentration<br/>Ion implantation: dopants are vaporized, accelecrated and directed at a Si substrate<br/>Diffusion: dopants diffuse from a high-concentration source into Si substrate
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Etch
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            Removal of specific material layers on the Si substrate<br/>Classified as dry and wet etch
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Photolithography
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            Uniformly covers of the substrate with photoresist<br/>Selectively exposes with a mask<br/>Develops the photoresist to define the desirable patterns<br/>Suitable for pattern definition with small feature sizes
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 underline">
            Isolation
            </p>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            Isolation is required from one active area to another<br/>Typical isolation is provided by a thick oxide layer (field oxide)<br/>Parasitic channel should be prevented under the field oxide<br/>Local oxideation of silicon (LOCOS) technique
            </p>
          </div>
        </section>
        <section className="min-h-screen" id="Simulation">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">Simulation</h3>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            A tool that is normally used for fabrication simulation is the SynopsysTM Technology Computer Aided Design (TCAD) software, specifically VisualFab, which will be utilised for Y4 microelectronics design modules.
            </p>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Process</h5>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            This template shows the process of making a simple Signal diode through ion implantation.
            </p>
            <Image src={sim4} class="rounded-xl" width={1000} height={500}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            The software will go through each stage of the fabrication, simulating the diffusion curves with the settings predefined by the user.
            </p>
            <div className="grid grid-cols-3 gap-4">
              <div className="bg-white">
              <Image src={sim1} class="rounded-xl" width={500} height={300}/>
              </div>
              <div className="bg-white">
              <Image src={sim2} class="rounded-xl" width={500} height={300}/>
              </div>
              <div className="bg-white">
                <Image src={sim3} class="rounded-xl" width={500} height={300}/>
              </div>
            </div>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
              The settings look like this:
            </p>
            <Image src={sim5} class="rounded-xl" width={600} height={600}/>
            <h5 className="text-2xl py-1 text-gray-800 dark:text-gray-200 font-bold mt-3">Fabrication of Zener Diode</h5>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            As mentioned earlier in the ‘Diode’ Section, Zener Diode are highly doped diodes which allow for Zener Breakdown to occur easily, allowing for flow of current in either directions.<br/>To achieve this highly doped junction, we will start off with the same substrate but ion implant both Boron (Blue) and Phosphorus(Red). Boron will be implanted first and will be deeper into the substrate.
            </p>
            <Image src={sim6} class="rounded-xl" width={950} height={500}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            The simulator has been configured to produce a concentration gradient that follows the gaussian function.<br/>Heat is then applied to spread the concentration evenly through diffusion. However, too much heat will increase diffusion, lowering the concentration below the intended 1018. Hence, for the sake of simplicity we will lower both the time and temperature of the heat treatment the wafer undergoes. This change can be made by changing the numerical value directly as  seen below:
            </p>
            <Image src={sim7} class="rounded-xl" width={600} height={400}/>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-200">
            The effect of the diffusion can be seen clearly as the concentration profile is now more evenly distributed across the cross-section of the wafer. Furthermore, it can be observed that the overall highest concentration of the substrate has decreased for both Boron and Phosphorus which aligns to the principle of gaussian profile of dopant concentration under thermal diffusion.
            </p>
            <Image src={sim8} class="rounded-xl" width={950} height={500}/>
          </div>
        </section>
        <section className="min-h-screen" id="About Us">
          <div className="h-24"></div>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 font-bold">About Us</h3>
            
          </div>
        </section>
      </main>
    </div>
  );
}
